import { useAdminThemeStore, type AdminTheme } from '../store/adminThemeStore';

export const ADMIN_THEME_CLASSES = {
  dark: {
    shell: 'bg-black text-white',
    sidebar: 'bg-neutral-950 border-white/[0.08]',
    topbar: 'bg-black/80 border-white/[0.08]',
    surface: 'bg-neutral-950 border-white/[0.08]',
    surfaceHover: 'hover:border-white/20 hover:shadow-2xl hover:shadow-orange-500/5',
    surfaceMuted: 'bg-neutral-900/50',
    heading: 'text-white',
    body: 'text-neutral-400',
    bodyStrong: 'text-neutral-300',
    muted: 'text-neutral-500',
    label: 'text-neutral-400',
    border: 'border-white/[0.08]',
    borderSubtle: 'border-white/[0.04]',
    borderStrong: 'border-white/10',
    divide: 'divide-white/[0.04]',
    divideStrong: 'divide-white/[0.06]',
    rowHover: 'hover:bg-white/[0.02]',
    navActive: 'bg-white/10 text-white font-semibold border border-white/10',
    navInactive: 'text-neutral-400 hover:text-neutral-200 hover:bg-white/[0.04]',
    iconBtn: 'border-white/[0.08] text-neutral-400 hover:text-white hover:bg-white/[0.04]',
    iconBtnActive: 'text-white bg-white/[0.04]',
    input: 'bg-neutral-950 border-white/[0.08] text-white placeholder-neutral-500',
    select: 'bg-neutral-950 border-white/[0.08] text-neutral-300',
    selectSmall: 'bg-neutral-900 border-white/10 text-white',
    secondaryBtn: 'bg-black hover:bg-neutral-950 text-white border-white/[0.08]',
    linkBack: 'text-neutral-400 hover:text-white',
    badge: 'bg-white/[0.06] text-white',
    dropdown: 'bg-neutral-950 border-white/[0.08] shadow-black/50',
    dropdownItemHover: 'hover:bg-white/[0.03]',
    overlay: 'bg-black/60',
    drawer: 'bg-neutral-950 border-white/[0.08]',
    loading: 'text-neutral-400',
    userEmail: 'text-neutral-200',
    cancelBtn: 'border-white/10 text-neutral-300 hover:bg-white/[0.04]',
    formInput: 'bg-[#111] border-white/10 text-white placeholder-neutral-500',
    arrowMuted: 'text-neutral-500 group-hover:text-white',
    refreshBtn:
      'bg-neutral-950 hover:bg-neutral-900 border-white/[0.08] text-neutral-300 hover:text-white',
    rowFocus: 'focus:bg-white/[0.04]',
    actionIconBtn: 'hover:bg-white/10 text-neutral-400 hover:text-white',
    iconClose: 'text-neutral-400 hover:text-white hover:bg-white/[0.06]',
  },
  light: {
    shell: 'bg-neutral-100 text-neutral-900',
    sidebar: 'bg-white border-neutral-200',
    topbar: 'bg-white/90 border-neutral-200',
    surface: 'bg-white border-neutral-200',
    surfaceHover: 'hover:border-neutral-300 hover:shadow-2xl hover:shadow-orange-500/10',
    surfaceMuted: 'bg-neutral-50',
    heading: 'text-neutral-900',
    body: 'text-neutral-600',
    bodyStrong: 'text-neutral-700',
    muted: 'text-neutral-500',
    label: 'text-neutral-500',
    border: 'border-neutral-200',
    borderSubtle: 'border-neutral-100',
    borderStrong: 'border-neutral-200',
    divide: 'divide-neutral-100',
    divideStrong: 'divide-neutral-200',
    rowHover: 'hover:bg-neutral-50',
    navActive: 'bg-neutral-100 text-neutral-900 font-semibold border border-neutral-200',
    navInactive: 'text-neutral-600 hover:text-neutral-900 hover:bg-neutral-50',
    iconBtn: 'border-neutral-200 text-neutral-600 hover:text-neutral-900 hover:bg-neutral-50',
    iconBtnActive: 'text-neutral-900 bg-neutral-50',
    input: 'bg-white border-neutral-200 text-neutral-900 placeholder-neutral-400',
    select: 'bg-white border-neutral-200 text-neutral-700',
    selectSmall: 'bg-white border-neutral-200 text-neutral-900',
    secondaryBtn: 'bg-white hover:bg-neutral-50 text-neutral-900 border-neutral-200',
    linkBack: 'text-neutral-600 hover:text-neutral-900',
    badge: 'bg-neutral-100 text-neutral-900',
    dropdown: 'bg-white border-neutral-200 shadow-neutral-300/40',
    dropdownItemHover: 'hover:bg-neutral-50',
    overlay: 'bg-neutral-900/40',
    drawer: 'bg-white border-neutral-200',
    loading: 'text-neutral-500',
    userEmail: 'text-neutral-800',
    cancelBtn: 'border-neutral-200 text-neutral-600 hover:bg-neutral-50',
    formInput: 'bg-white border-neutral-200 text-neutral-900 placeholder-neutral-400',
    arrowMuted: 'text-neutral-400 group-hover:text-neutral-900',
    refreshBtn:
      'bg-white hover:bg-neutral-50 border-neutral-200 text-neutral-600 hover:text-neutral-900',
    rowFocus: 'focus:bg-neutral-100',
    actionIconBtn: 'hover:bg-neutral-100 text-neutral-500 hover:text-neutral-900',
    iconClose: 'text-neutral-500 hover:text-neutral-900 hover:bg-neutral-100',
  },
} as const satisfies Record<AdminTheme, Record<string, string>>;

export type AdminThemeClasses = (typeof ADMIN_THEME_CLASSES)[AdminTheme];

export function useAdminThemeClasses(): AdminThemeClasses {
  const theme = useAdminThemeStore((state) => state.theme);
  return ADMIN_THEME_CLASSES[theme];
}
