import { Product, SignatureKit, ComboOffer } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'All Products' },
  { id: 'best-sellers', name: 'Best Sellers' },
  { id: 'new-arrivals', name: 'New Arrivals' },
];

export const PRODUCTS: Product[] = [
  // Best Sellers
  {
    id: 'chicken-masala',
    name: 'Chicken Masala',
    description: 'Classic chicken masala blend.',
    price: 100,
    weight: '100g',
    category: 'best-sellers',
    image: '/images/products/chicken-masala.png',
    color: 'from-orange-500 to-red-600',
    isSignatureKit: false,
  },
  {
    id: 'mutton-masala',
    name: 'Mutton Masala',
    description: 'Robust mutton masala blend.',
    price: 100,
    weight: '100g',
    category: 'best-sellers',
    image: '/images/products/mutton-masala.png',
    color: 'from-red-600 to-rose-900',
    isSignatureKit: false,
  },
  {
    id: 'fish-masala',
    name: 'Fish Masala',
    description: 'Coastal-style fish masala blend.',
    price: 100,
    weight: '100g',
    category: 'best-sellers',
    image: '/images/products/fish-masala.png',
    color: 'from-rose-500 to-red-600',
    isSignatureKit: false,
  },
  {
    id: 'egg-masala',
    name: 'Egg Masala',
    description: 'Everyday egg masala blend.',
    price: 100,
    weight: '100g',
    category: 'best-sellers',
    image: '/images/products/egg-masala.png',
    color: 'from-yellow-500 to-orange-600',
    isSignatureKit: false,
  },
  {
    id: 'chicken-masala-for-children',
    name: 'Chicken Masala for Children',
    description: 'Milder chicken masala for children.',
    price: 100,
    weight: '100g',
    category: 'best-sellers',
    image: '/images/products/chicken-masala-for-children.png',
    color: 'from-amber-500 to-orange-600',
    isSignatureKit: false,
  },
  {
    id: 'kabab-masala',
    name: 'Kabab Masala',
    description: 'Aromatic kabab masala blend.',
    price: 100,
    weight: '100g',
    category: 'best-sellers',
    image: '/images/products/kabab-masala.png',
    color: 'from-orange-600 to-red-700',
    isSignatureKit: false,
  },

  // New Arrivals
  {
    id: 'pepper-fry-masala',
    name: 'Pepper Fry Masala',
    description: 'Bold pepper fry masala blend.',
    price: 200,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/pepper-fry-masala.png',
    color: 'from-neutral-800 to-black',
    isSignatureKit: false,
    weightVariants: [
      { weight: '100g', price: 200 },
      { weight: '250g', price: 500 },
      { weight: '500g', price: 1000 },
      { weight: '1kg', price: 2000 },
    ],
  },
  {
    id: 'roasted-chilli',
    name: 'Roasted Chilli',
    description: 'Roasted chilli powder.',
    price: 100,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/roasted-chilli.png',
    color: 'from-red-500 to-red-800',
    isSignatureKit: false,
  },
  {
    id: 'roasted-coriander',
    name: 'Roasted Coriander',
    description: 'Roasted coriander powder.',
    price: 100,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/roasted-coriander.png',
    color: 'from-green-600 to-green-800',
    isSignatureKit: false,
  },
  {
    id: 'kashmiri-chilli',
    name: 'Kashmiri Chilli',
    description: 'Kashmiri chilli powder.',
    price: 100,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/kashmiri-chilli.png',
    color: 'from-red-500 to-rose-700',
    isSignatureKit: false,
  },
  {
    id: 'turmeric-powder',
    name: 'Turmeric Powder',
    description: 'Pure turmeric powder.',
    price: 100,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/turmeric-powder.png',
    color: 'from-yellow-300 to-amber-500',
    isSignatureKit: false,
  },
  {
    id: 'roasted-jeera-powder',
    name: 'Roasted Jeera Powder',
    description: 'Roasted cumin powder.',
    price: 100,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/roasted-jeera-powder.png',
    color: 'from-stone-600 to-stone-800',
    isSignatureKit: false,
  },
  {
    id: 'pepper-powder',
    name: 'Pepper Powder',
    description: 'Ground black pepper powder.',
    price: 100,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/pepper-powder.png',
    color: 'from-neutral-700 to-black',
    isSignatureKit: false,
  },
  {
    id: 'chutney-powder',
    name: 'CHATTNI POWDER',
    description: 'Dry chattni powder.',
    price: 100,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/chutney-powder.png',
    color: 'from-lime-500 to-green-700',
    isSignatureKit: false,
  },
  {
    id: 'rasam-powder',
    name: 'Rasam Powder',
    description: 'Traditional rasam powder.',
    price: 100,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/rasam-powder.png',
    color: 'from-amber-600 to-orange-800',
    isSignatureKit: false,
  },
  {
    id: 'sambar-powder',
    name: 'Sambar Powder',
    description: 'Traditional sambar powder.',
    price: 100,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/sambar-powder.png',
    color: 'from-orange-700 to-amber-900',
    isSignatureKit: false,
  },
  {
    id: 'garam-masala',
    name: 'Garam Masala',
    description: 'Classic garam masala blend.',
    price: 100,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/garam-masala.png',
    color: 'from-amber-700 to-orange-950',
    isSignatureKit: false,
  },
  {
    id: 'channa-masala',
    name: 'Channa Masala',
    description: 'Channa / chole masala blend.',
    price: 100,
    weight: '100g',
    category: 'new-arrivals',
    image: '/images/products/channa-masala.png',
    color: 'from-orange-800 to-amber-900',
    isSignatureKit: false,
  },
];

export const COMBO_OFFERS: ComboOffer[] = [
  {
    id: 'combo-offer-1',
    title: 'Combo Offer 1',
    offerPrice: 950,
    totalWeight: '1,200 gms',
    image: '/images/offers/combo-offer-1.png',
    items: [
      { name: 'Chicken Masala', weight: '100 gms', price: 100 },
      { name: 'Chicken Masala for Children', weight: '100 gms', price: 100 },
      { name: 'Mutton Masala', weight: '100 gms', price: 100 },
      { name: 'Fish Masala', weight: '100 gms', price: 100 },
      { name: 'Egg Masala', weight: '100 gms', price: 100 },
      { name: 'Kabab Masala', weight: '100 gms', price: 100 },
      { name: 'Pepper Fry Masala', weight: '100 gms', price: 200 },
      { name: 'Dry Coconut Chattni Powder', weight: '500 gms', price: 400 },
    ],
  },
  {
    id: 'combo-offer-2',
    title: 'Combo Offer 2',
    offerPrice: 950,
    totalWeight: '1,200 gms',
    image: '/images/offers/combo-offer-1.png',
    items: [
      { name: 'Roasted Chilli', weight: '100 gms', price: 100 },
      { name: 'Roasted Coriander', weight: '100 gms', price: 100 },
      { name: 'Kashmiri Chilli', weight: '100 gms', price: 100 },
      { name: 'Turmeric Powder', weight: '100 gms', price: 100 },
      { name: 'Roasted Jeera Powder', weight: '100 gms', price: 100 },
      { name: 'Pepper Powder', weight: '100 gms', price: 200 },
      { name: 'Rasam Powder', weight: '100 gms', price: 100 },
      { name: 'Sambar Powder', weight: '100 gms', price: 100 },
      { name: 'Garam Masala', weight: '100 gms', price: 100 },
      { name: 'Channa Masala', weight: '100 gms', price: 100 },
      { name: 'Chattni Powder', weight: '100 gms', price: 100 },
    ],
  },
  {
    id: 'combo-offer-3',
    title: 'Combo Offer 3',
    offerPrice: 1140,
    totalWeight: '18 × 60 gms + Chattni 400 gms',
    image: '/images/offers/combo-offer-1.png',
    items: [
      { name: 'Chicken Masala', weight: '60 gms' },
      { name: 'Chicken Masala for Children', weight: '60 gms' },
      { name: 'Mutton Masala', weight: '60 gms' },
      { name: 'Fish Masala', weight: '60 gms' },
      { name: 'Egg Masala', weight: '60 gms' },
      { name: 'Kabab Masala', weight: '60 gms' },
      { name: 'Pepper Fry Masala', weight: '60 gms' },
      { name: 'Roasted Chilli', weight: '60 gms' },
      { name: 'Roasted Coriander', weight: '60 gms' },
      { name: 'Kashmiri Chilli', weight: '60 gms' },
      { name: 'Turmeric Powder', weight: '60 gms' },
      { name: 'Roasted Jeera Powder', weight: '60 gms' },
      { name: 'Pepper Powder', weight: '60 gms' },
      { name: 'CHATTNI POWDER', weight: '60 gms' },
      { name: 'Rasam Powder', weight: '60 gms' },
      { name: 'Sambar Powder', weight: '60 gms' },
      { name: 'Garam Masala', weight: '60 gms' },
      { name: 'Channa Masala', weight: '60 gms' },
      { name: 'Chattni Powder', weight: '400 gms' },
    ],
  },
];

export function comboOfferToProduct(offer: ComboOffer): Product {
  return {
    id: offer.id,
    name: offer.title,
    description: 'Introductory Launch Offer hamper.',
    price: offer.offerPrice,
    weight: offer.totalWeight,
    category: 'offers',
    image: offer.image,
    color: 'from-orange-500 to-red-600',
    isSignatureKit: false,
  };
}

export function getComboOfferById(id: string): ComboOffer | undefined {
  return COMBO_OFFERS.find((offer) => offer.id === id);
}

export const SIGNATURE_KITS: SignatureKit[] = [];
